---
title: "R Notebook"
output: html_notebook
---

```{r}
#Accessing libraries
library(googleAnalyticsR)
library(keyring)
```

```{r}
# keyring_create(keyring = "googleanalytics")
# 
# key_set(service = "ga_client_id", keyring = "googleanalytics")
# key_set(service = "ga_client_secret", keyring = "googleanalytics")
# 
# keyring_lock(keyring = "googleanalytics")
```

```{r}

# Setting options(googleAuthR.client_id) and options(googleAuthR.client_secret) to activate API call
options(googleAuthR.client_id = keyring::key_get(service = "ga_client_id", keyring = "googleanalytics"))
options(googleAuthR.client_secret = keyring::key_get(service = "ga_client_secret", keyring = "googleanalytics"))

# reloading package
devtools::reload(pkg = devtools::inst("googleAnalyticsR"))

#Authenticating account
ga_auth()
```

```{r}


#Get a list of accounts you have access to
account_list <- ga_account_list()

#ViewID is the way to access the account you want
account_list$viewId

#Select the one you want to work with
my_ga_id <- 123456

#Call the API to access the data you require
google_analytics(my_ga_id, 
                 date_range = c("2019-01-01", "2019-03-01"), 
                 metrics = "sessions", 
                 dimensions = "date")
```

