---
title: "R Notebook"
output: html_notebook
---
```{r}
#Accessing libraries
library(googleAnalyticsR)
library(keyring)
library(janitor)
library(tidyverse)
library(lubridate)
library(scales)
```

```{r}

keyring_unlock(keyring = "googleanalytics")
# Setting options(googleAuthR.client_id) and options(googleAuthR.client_secret) to activate API call
options(googleAuthR.client_id = keyring::key_get(service = "ga_client_id", keyring = "googleanalytics"))
options(googleAuthR.client_secret = keyring::key_get(service = "ga_client_secret", keyring = "googleanalytics"))

# reloading package
devtools::reload(pkg = devtools::inst("googleAnalyticsR"))

#Authenticating account

ga_auth()

keyring_lock(keyring = "googleanalytics")
```

```{r}

#Get a list of accounts you have access to
account_list <- ga_account_list()

account_list

#ViewID is the way to access the account you want
account_list$viewId

#Select the one you want to work with
my_ga_id <- 102407343

#Call the API to access the data you require
user_journey_data <- google_analytics(my_ga_id,
                 date_range = c("2018-12-01", "2019-12-01"),
                 metrics = c(
                   "sessions", 
                   "bounceRate", 
                   "exitRate", 
                   "avgTimeOnPage", 
                   "goal3Completions", 
                   "goal5Completions"),
                 dimensions = c(
                   "date",
                   "channelGrouping", 
                   "deviceCategory", 
                   "landingPagePath", 
                   "secondPagePath"
                   ),
                 max = -1,
                 anti_sample = TRUE
                 )
```


```{r}
clean_user_journey_data <- clean_names(user_journey_data) 


clean_user_journey_data %>%
  mutate(
    bounce_rate = round(bounce_rate, 2),
    exit_rate = round(exit_rate, 2)
    )
```

```{r}
user_journey_data %>%
  group_by(landingPagePath) %>%
  summarise(total_sessions = sum(sessions)) %>%
  arrange(desc(total_sessions))


user_journey_data %>%
  group_by(month(date, label = TRUE)) %>%
  summarise(total_sessions = sum(sessions)) %>%
  arrange(desc(total_sessions))


```



